# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "members" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"login" varchar(50) NOT NULL,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"uid" VARCHAR NOT NULL,"suscribeDate" DATE NOT NULL,"lastConnectDate" DATE NOT NULL,"isActive" BOOLEAN NOT NULL,"sex" varchar(1),"firstName" VARCHAR,"lastName" VARCHAR,"birthDate" DATE,"city" varchar(100),"securityKey" VARCHAR,"token" VARCHAR,"expirationToken" DATE);

# --- !Downs

drop table "members";

