# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "members" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"login" varchar(50) NOT NULL,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"uid" VARCHAR NOT NULL,"suscribeDate" TIMESTAMP NOT NULL,"lastConnectDate" TIMESTAMP NOT NULL,"isActive" BOOLEAN NOT NULL,"sex" varchar(1),"firstName" VARCHAR,"lastName" VARCHAR,"birthDate" TIMESTAMP,"city" varchar(100),"description" varchar(255),"mainPicture" BIGINT,"securityKey" VARCHAR,"token" VARCHAR,"expirationToken" TIMESTAMP);
create table "photos" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"login" VARCHAR NOT NULL,"contentType" VARCHAR NOT NULL,"email" INTEGER NOT NULL,"password" BOOLEAN NOT NULL);

# --- !Downs

drop table "members";
drop table "photos";

